blog/urls.py
from django.conf.urls import url

from . import views

app_name='blog'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^about/', views.about, name='about'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^archive/$', views.ArchiveView.as_view(), name='archive'),
    url(r'^tech/$', views.tech, name='tech'),
    url(r'^(?P<blog_id>[0-9]+)/comment/$', views.comment, name='comment'),
]

cs2610new/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^gold/', include('gold.urls', namespace="gold")),
    url(r'^goldconvert/', include('goldconvert.urls', namespace="goldconvert")),
    url(r'^admin/', admin.site.urls),
]

gold/urls.py
from django.conf.urls import url, include

from . import views

app_name='gold'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^goldconvert/', include('goldconvert.urls'))
]

goldconvert/urls.py
from django.conf.urls import url

from . import views

app_name='goldconvert'

urlpatterns = [
    url(r'^', views.conversion, name="conversion")
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import datetime

from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=200)
    auth_name = models.CharField(max_length=50)
    content = models.TextField(max_length=25000)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.title
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    content = models.TextField(max_length=2000)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.content

gold/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

goldconvert/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class conversionFactor(models.Model):
    unit = models.CharField(max_length=10)
    factor = models.FloatField()

polls/models.py
from __future__ import unicode_literals

from django.db import models

import datetime

from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

blog/views.py
from django.http import HttpResponseRedirect
from .models import Blog, Comment
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
import datetime

class HomeView(generic.ListView):
    template_name='blog/home.html'
    context_object_name='latest_blog_list'
    
    def get_queryset(self):
        return Blog.objects.order_by('-pub_date')[:3]

class ArchiveView(generic.ListView):
    template_name='blog/archive.html'
    context_object_name='blog_list'
    
    def get_queryset(self):
        return Blog.objects.order_by('-pub_date')
        
class DetailView(generic.DetailView):
    model=Blog
    template_name='blog/detail.html'
    
def tech(request):
    return render(request, 'blog/tech.html')
    
def about(request):
    return render(request, 'blog/about.html')
    
def comment(request, blog_id):
    form_data = request.POST
    blog_obj = get_object_or_404(Blog, pk=blog_id)
    new_comment = Comment(blog=blog_obj, nickname=form_data.__getitem__('nickname'), email=form_data.__getitem__('email'), content=form_data.__getitem__('comment'), pub_date=datetime.datetime.now())
    new_comment.save()
    
    return redirect('blog:detail', pk=blog_id)

gold/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'gold/index.html')

goldconvert/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from models import conversionFactor

# Create your views here.
def conversion(request):
    fromUnit = request.GET['from']
    toUnit = request.GET['to']
    weight = float(request.GET['value'])
    
    fromConversion = conversionFactor.objects.get(unit=fromUnit)
    fromFactor = fromConversion.factor
    
    toConversion = conversionFactor.objects.get(unit=toUnit)
    toFactor = toConversion.factor
    
    endWeight = weight * fromFactor / toFactor
    print(endWeight)
    response = JsonResponse({'unit':toUnit, 'value':endWeight})
    
    return response

polls/views.py
from django.http import HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}
    About Taako
{% endblock %}

{% block main %}
    <h1>About Me</h1>
    <div class="flex">
        <article class="flex">
            <div><img src="taako.jpg" alt="Taako"></div>
            <div>
                <h2>Hey There</h2>
                <p>My name's Taako. You may recognize me from my cooking show, <i>Sizzlin' It Up With Taako</i>. If not, you may have heard of my many great accomplishments as a member of an elite squad of Reclaimers for the Bureau of Balance. It's all strictly classified, but I'm sure Angus has blabbed some of it to the general public.</p>
                <p>Anyhoo, enjoy the blog. I've got a universe or two to save. I think the site's about web design or some mumbo jumbo like that? Go hog wild, boss.</p>
            </div>
        </article>
    </div>
{% endblock %}

blog/templates/blog/archive.html
{% extends 'blog/base.html' %}

{% block title %}
    Taako's Blog Archive
{% endblock %}

{% block relative_path %}
..
{% endblock %}

{% block main %}
    <h1>Archive</h1>
    {% if blog_list %}
        <div class="flex">
            <div class="flexcol">
                {% for blog in blog_list %}
                    <article class="blog">
                        <h2>
                            <a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>
                        </h2>
                        <p>
                            {{ blog.content|truncatewords:200 }}
                        </p>
                        <p>
                            {{ blog.comment_set.count }} Comment{% if blog.comment_set.count != 1 %}s{% endif %}
                        </p>
                    </article>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No blogs are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="../../static/stylesheet.css">
    </head>
    <body>
        <header>
            <h2>A Snazzy Yet Classy Title</h2>
            <nav>
                <ul></ul>
                    <li><a href="{% url 'blog:home' %}">Home</a></li>
                    <li><a href="{% url 'blog:about' %}">About Me</a></li>
                    <li><a href="{% url 'blog:tech' %}">Tech Tips</a></li>
                    <li><a href="{% url 'blog:archive' %}">Archive</a></li>
                </ul>
            </nav>
        </header>
        <main>
            {% block main %}
            {% endblock %}
            <aside>
                <h2>Sidebar</h2>
                Welcome to the Sidebar, a bar on the side. Looking for a drink, good music, or just a place to hang out, but all in a more horizontal orientation? Then this is the place for you. But what's this? We've switched it up today, and the Sidebar is on the bottom. Oooooh!
            </aside>
        </main>
        <footer>
            Copyright Nate Lovell 2073.
        </footer>
    </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block main %}
    <article>
        <h1>
            {{ blog.title }}
        </h1>
        <p>
            {{ blog.auth_name }}
        </p>
        <p>
            {{ blog.pub_date }}
        </p>
        <p>
            {{ blog.content }}
        </p>
    </article>
    <hr>
    <h2>
        Comments ({{blog.comment_set.count}})
    </h2>
    <form action="{% url 'blog:comment' blog.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Add a Comment</legend>
            <label>
                Nickname*:<br>
                <input type="text" name="nickname" aria-required="true">
            </label><br>
            <label>
                Email Address*:<br>
                <input type="email" name="email" aria-required="true">
            </label><br>
            <label>
                Comment*<br>
                <textarea name="comment" aria-required="true"></textarea>
            </label><br>
            <center>
                <button type="submit">Post Comment</button>
            </center>
        </fieldset>
    </form>
    {% if blog.comment_set.all %}
        <div class="comment">
            {% for comment in blog.comment_set.all reversed %}
                <article>
                    <h3>
                        {{ comment.nickname }}
                    </h3>
                    <div class="emailAndDate">
                        <a href="mailto:{{ comment.email }}">{{ comment.email }}</a> | {{ comment.pub_date }}
                    </div>
                    <p {% if comment.content.length < 30 %}class="shortComment"{% endif %}>
                        {{ comment.content }}
                    </p>
                    <hr>
                </article>
            {% endfor %}
        </div>
    {% else %}
        <p class="noComments">There are no comments on this post.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}
    Taako's Blog
{% endblock %}

{% block relative_path %}
{% endblock %}

{% block main %}
    <h1>Home</h1>
    {% if latest_blog_list %}
        <div class="flex">
            <div class="flexcol">
                {% for blog in latest_blog_list %}
                    <article class="blog">
                        <h2>
                            <a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>
                        </h2>
                        <p>
                            {{ blog.content|truncatewords:200 }}
                        </p>
                        <p>
                            {{ blog.comment_set.count }} Comment{% if blog.comment_set.count != 1 %}s{% endif %}
                        </p>
                    </article>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No blogs are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/tech.html
{% extends 'blog/base.html' %}

{% block title %}
    Taako's Tech Cheat Sheet
{% endblock %}

{% block main %}
    <h1>Taako's Tech Cheat Sheet</h1>
    <p>Welcome to my tech cheat sheet! Here you'll find a list of helpful git commands, their descriptions, and working examples. You'll also find HTML tags and CSS styles.<br>
    Alternatively, see the <a href="https://git-scm.com/documentation">full documentation for git</a>, the <a href="https://www.w3schools.com/html/html_intro.asp">W3Schools HTML documentation</a>, or the <a href="https://www.w3schools.com/css/default.asp">W3Schools CSS documentation</a>.</p>
    <p>The <code>.hidden</code> CSS class was borrowed from <a href="https://webaim.org/techniques/css/invisiblecontent/">WebAIM's tutorial on creating invisible content</a> that is accessible to screen reader users. This class is used to provide alternative text for CSS background images.</p>
    <article class="flexrow">
        <h2 class="articleheader">Tech Tables</h2>
        <div id="git">
        <table class="bgfixed">
            <caption>Git Commands</caption>
            <thead>
                <tr>
                    <th scope="col">Command</th>
                    <th scope="col">Description</th>
                    <th scope="col">Example</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>git init</td>
                    <td>Creates a git repository in the current directory.</td>
                    <td>git init</td>
                </tr>
                <tr>
                    <td>git add</td>
                    <td>Displays the sum of all files in the repository.</td>
                    <td>git add</td>
                </tr>
                <tr>
                    <td>git commit</td>
                    <td>Saves changes to the local repository. (May prompt awkward conversation if repository isn't ready for that kind of thing.)</td>
                    <td>git commit -m "I'm ready to take this to the next level."</td>
                </tr>
                <tr>
                    <td>git push</td>
                    <td>Pushes saved changes down the tubes to a remote repository. If tubes are clogged, apply pipe snake as needed.</td>
                    <td>git push really hard</td>
                </tr>
                <tr>
                    <td>git go back</td>
                    <td>The git equivalent of ctrl + Z. Undoes whatever you screwed up.</td>
                    <td>git go back!!1!</td>
                </tr>
                <tr>
                    <td>git woo</td>
                    <td>Reassures repository after a failed commit.</td>
                    <td>git woo -m "I'm a different person now."</td>
                </tr>
                <tr>
                    <td>git django</td>
                    <td>Releases a python.</td>
                    <td id="python" class="image"><span class="hidden">A python</span></td>
                </tr>
                <tr>
                    <td>git freaky</td>
                    <td>Gives the repository a bottle of bourbon and tells it to have a good time.</td>
                    <td>git freaky, git freaky, everybody in the house git freaky.</td>
                </tr>
                <tr>
                    <td>git r'lyeh</td>
                    <td>Awakens the Great Old Ones from their eternal slumber. Launches the earth into an unending age of blood and darkness. May corrupt repository.</td>
                    <td class="image" id="darkness"><span class="hidden">Eternal darnkess</span></td>
                </tr>
            </tbody>
        </table>
        </div>
        <div id="css">
        <table class="bglocal">
            <caption>CSS Styles</caption>
            <thead>
                <tr>
                    <th scope="col">Style</th>
                    <th scope="col">Description</th>
                    <th scope="col">Example</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>display</td>
                    <td>Determines how an element is displayed on the page.</td>
                    <td>.invisible{display:none}</td>
                </tr>
                <tr>
                    <td>border-style</td>
                    <td>Stands outside the border's dressing room during a shopping montage, giving it advice on which outfit to buy.</td>
                    <td>border-style{Uh-uh. Uh-uh. That's the one.}</td>
                </tr>
                <tr>
                    <td>WYWIWYG</td>
                    <td>A magical style that allows you to telepathically communicate the style you're going for to the browser, so it can just do what you want it to instead of making you mess around with spacing for hours.</td>
                    <td>WYWIWYG{I just want a simple sidebar, is that too much to ask?!}</td>
                </tr>
            </tbody>
        </table>
        </div>
        <div id="html">
        <table class="bgscroll">
            <caption>HTML Tags</caption>
            <thead>
                <tr>
                    <th scope="col">Tag</th>
                    <th scope="col">Description</th>
                    <th scope="col">Example</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>&lt;;html&gt;;</td>
                    <td>Contains an HTML document.</td>
                    <td>&lt;;html&gt;;(everything else goes here)&lt;;/html&gt;;</td>
                </tr>
                <tr>
                    <td>&lt;b&gt;</td>
                    <td>Makes text bold.</td>
                    <td>&lt;b&gt;You said WHAT?!?&lt;/b&gt;</td>
                </tr>
                <tr>
                    <td>&lt;a&gt;</td>
                    <td>Makes an element into the "Alpha" element, giving it superior social status to its peers.</td>
                    <td>&lt;a&gt;I'm the captain now.&lt;/a&gt;</td>
                </tr>
                <tr>
                    <td>&lt;fin&gt;</td>
                    <td>Either terminates the current document, or renders ASCII art of a shark's dorsal fin, depending on the browser.</td>
                    <td>&lt;fin&gt;</td>
                </tr>
            </tbody>
        </table>
        </div>
    </article>
{% endblock %}

gold/templates/gold/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'gold/style.css' %}" />
        <script src="{% static 'gold/script.js' %}"></script>
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>
    <body onload="setHandlers()">
        <header>
            <a href="{% url 'gold:index' %}"><h2>Goldz-Arr-Uss <img src="{% static 'gold/images/checkmark.png' %}" alt=""></h2></a>
            <em>Gold you can count on.</em>
        </header>
        <main>
             {% block content %}
             {% endblock %}
        </main>
        <footer>
            <p>Copyright Goldz-Arr-Uss 2017.</p>
            <p>Instructions for generating this web app were provided by the <a href="https://docs.djangoproject.com/en/1.11/intro/tutorial01/">Django Software Foundation</a>.</p>
            <p>The checkmark icon in the header was found at <a href="http://weclipart.com/yes+check+mark+clip+art">Weclipart</a>.</p>
        </footer>
    </body>
</html>

gold/templates/gold/index.html
{% extends 'gold/base.html' %}

{% block title %}
    Goldz-Arr-Uss
{% endblock %}

{% block content %}
    <h1>You're worth you're weight in gold!</h1>
    <p>
        Welcome to Goldz-Arr-Uss. Here at Goldz-Arr-Uss, we believe that you're worth your weight in gold! How much is that exactly? Well type in your weight below and have a look-see, why doncha?
    </p>
    <fieldset>
        <legend>
            Enter your weight
        </legend>
        <p>
            <label>
                Weight<span style="color:#c00;" aria-hidden="true">*</span>:
                <input type="text" name="weight" id="weight" aria-required="true" aria-describedby="weightError">
                <p id="weightError"></p>
            </label>
        </p>
        <p>
            <label>
                Unit of Measure<span style="color:#c00;" aria-hidden="true">*</span>:
                <select name="fromUnit" id="fromUnit" aria-required="true">
                    <option value="lb" selected>Pounds (lbs)</option>
                    <option value="kg">Kilograms (kgs)</option>
                    <option value="g">Grams (g)</option>
                    <option value="N">Newtons (N)</option>
                    <option value="t_oz">Troy Ounces (oz t)</option>
                </select>
            </label>
        </p>
        <p class="center">
            <input type="submit" id="submitWeight">
        </p>
    </fieldset>
    <div id="results"></div>
{% endblock %}

polls/templates/polls/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
        <title>Polls Home</title>
    </head>
    <body>
        <header>
            <a href="{% url 'polls:index' %}"><h2>Polls-Arr-Uss <img src="{% static 'polls/images/checkmark.png' %}" alt=""></h2></a>
            <em>Polling you can count on.</em>
        </header>
        <main>
             {% block content %}
             {% endblock %}
        </main>
        <footer>
            <p>Copyright Polls-Arr-Uss 2017.</p>
            <p>Instructions for generating this web app were provided by the <a href="https://docs.djangoproject.com/en/1.11/intro/tutorial01/">Django Software Foundation</a>.</p>
            <p>The checkmark icon in the header was found at <a href="http://weclipart.com/yes+check+mark+clip+art">Weclipart</a>.</p>
        </footer>
    </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <p class="center"><input type="submit" value="Vote" /></p>
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
    <h1>Home</h1>
    <p>
        Welcome to Polls-Arr-Uss. Here at Polls-Arr-Uss, we're dedicated to learning the real human answers to real human questions. Questions like "How many type can't a dog cloud?" and "Did German none left beef?" Below, you'll find a list of our most recent polls.
    </p>
    <h2>Most Recent Polls</h2>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %} 
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>
    
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}